// GENERATED by scripts/sync-domain.mjs from src/domain. Do not edit.
/**
 * Expense validation shared by the app (before writing locally) and the server
 * (before accepting a synced write). Pure TypeScript, zero dependencies.
 */
import type { PayerLine } from './balances.ts';
import type { Paise } from './money.ts';
import {
  computeSplit,
  type MemberId,
  type ShareLine,
  type SplitError,
  type SplitInput,
} from './splits.ts';

export const MAX_DESCRIPTION_LENGTH = 100;

export interface ExpenseInput {
  description: string;
  amountPaise: Paise;
  /** Local calendar date 'YYYY-MM-DD'. */
  expenseDate: string;
  payers: readonly PayerLine[];
  splitInput: SplitInput;
}

export type ExpenseValidationError =
  | { code: 'DESCRIPTION_REQUIRED' }
  | { code: 'DESCRIPTION_TOO_LONG'; max: number }
  | { code: 'INVALID_DATE' }
  | { code: 'INVALID_PAYERS' }
  | { code: 'PAYER_SUM_MISMATCH'; expected: Paise; actual: Paise }
  | { code: 'UNKNOWN_MEMBER'; memberId: MemberId }
  | { code: 'SPLIT'; error: SplitError };

export type ExpenseValidationResult =
  | { ok: true; description: string; payers: PayerLine[]; shares: ShareLine[] }
  | { ok: false; error: ExpenseValidationError };

const fail = (error: ExpenseValidationError): ExpenseValidationResult => ({ ok: false, error });

/** True only for real calendar dates in 'YYYY-MM-DD' form (rejects 2026-02-30). */
export function isValidCalendarDate(value: string): boolean {
  const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(Date.UTC(year, month - 1, day));
  return (
    date.getUTCFullYear() === year && date.getUTCMonth() === month - 1 && date.getUTCDate() === day
  );
}

/** Every member referenced by a split input, including zero-valued entries. */
function splitMemberIds(input: SplitInput): MemberId[] {
  switch (input.type) {
    case 'equal':
      return input.memberIds;
    case 'exact':
    case 'percentage':
    case 'shares':
      return input.entries.map((e) => e.memberId);
    case 'itemized':
      return input.items.flatMap((item) => item.memberIds);
  }
}

/**
 * Validate an expense against the members allowed on it.
 * On success returns normalized values ready to persist: trimmed description,
 * payers without zero lines, and computed shares.
 */
export function validateExpense(
  input: ExpenseInput,
  allowedMemberIds: ReadonlySet<MemberId>,
): ExpenseValidationResult {
  const description = input.description.trim().replace(/\s+/g, ' ');
  if (description === '') return fail({ code: 'DESCRIPTION_REQUIRED' });
  if (description.length > MAX_DESCRIPTION_LENGTH) {
    return fail({ code: 'DESCRIPTION_TOO_LONG', max: MAX_DESCRIPTION_LENGTH });
  }
  if (!isValidCalendarDate(input.expenseDate)) return fail({ code: 'INVALID_DATE' });

  const split = computeSplit(input.amountPaise, input.splitInput);
  if (!split.ok) return fail({ code: 'SPLIT', error: split.error });

  if (input.payers.length === 0) return fail({ code: 'INVALID_PAYERS' });
  const payerIds = new Set<MemberId>();
  let paid = 0;
  for (const payer of input.payers) {
    if (
      !payer.memberId ||
      payerIds.has(payer.memberId) ||
      !Number.isSafeInteger(payer.amountPaise) ||
      payer.amountPaise < 0
    ) {
      return fail({ code: 'INVALID_PAYERS' });
    }
    payerIds.add(payer.memberId);
    paid += payer.amountPaise;
  }
  if (paid !== input.amountPaise) {
    return fail({ code: 'PAYER_SUM_MISMATCH', expected: input.amountPaise, actual: paid });
  }

  for (const memberId of [...payerIds, ...splitMemberIds(input.splitInput)]) {
    if (!allowedMemberIds.has(memberId)) return fail({ code: 'UNKNOWN_MEMBER', memberId });
  }

  return {
    ok: true,
    description,
    payers: input.payers
      .filter((p) => p.amountPaise > 0)
      .map((p) => ({ memberId: p.memberId, amountPaise: p.amountPaise })),
    shares: split.shares,
  };
}