// GENERATED by scripts/sync-domain.mjs from src/domain. Do not edit.
/**
 * Expense notes and receipt references. Pure TypeScript, zero dependencies: copied to the Edge
 * Function by `npm run domain:sync`, so the server checks exactly what the app writes.
 */

/** Longest note, in characters (UTF-16 code units, like the database's char_length for BMP text). */
export const MAX_NOTE_LENGTH = 500;

export type NoteResult = { ok: true; note: string | null } | { ok: false; error: 'TOO_LONG' };

/**
 * Canonical form of a typed note: Windows line breaks unified, control characters other than
 * newline and tab removed, runs of blank lines collapsed to one, ends trimmed. Empty → null.
 */
export function normalizeNote(input: string | null | undefined): NoteResult {
  if (input == null) return { ok: true, note: null };
  const cleaned = input
    .replace(/\r\n?/g, '\n')
    .replace(/[\u0000-\u0008\u000B-\u001F\u007F]/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  if (cleaned === '') return { ok: true, note: null };
  if (cleaned.length > MAX_NOTE_LENGTH) return { ok: false, error: 'TOO_LONG' };
  return { ok: true, note: cleaned };
}

/** True for null or a note exactly as normalizeNote stores it (server-side check). */
export function isCanonicalNote(value: unknown): value is string | null {
  if (value === null) return true;
  if (typeof value !== 'string') return false;
  const result = normalizeNote(value);
  return result.ok && result.note === value;
}

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

/** Receipt ids are lowercase UUIDs: they become part of a storage path. */
export const isReceiptId = (value: unknown): value is string =>
  typeof value === 'string' && UUID.test(value);

/** Storage object name of a receipt photo: "<group>/<expense>/<receipt>.jpg". */
export const receiptObjectPath = (groupId: string, expenseId: string, receiptId: string): string =>
  `${groupId.toLowerCase()}/${expenseId.toLowerCase()}/${receiptId}.jpg`;
