// Copies src/domain (pure TypeScript) into supabase/functions/_shared/domain so the
// sync-push Edge Function validates expenses with exactly the code the app runs.
// Deno requires explicit file extensions, so relative imports get ".ts" appended.
// Run: npm run domain:sync — and commit the result (CI fails if it is stale).
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

const SRC = 'src/domain';
const OUT = 'supabase/functions/_shared/domain';
const HEADER = '// GENERATED by scripts/sync-domain.mjs from src/domain. Do not edit.\n';

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

let count = 0;
for (const name of readdirSync(SRC)) {
  if (!name.endsWith('.ts') || name.endsWith('.test.ts')) continue;

  const source = readFileSync(join(SRC, name), 'utf8');
  if (/from\s+['"](?!\.\/)/.test(source)) {
    console.error(`${SRC}/${name}: only same-folder relative imports are allowed (domain must stay dependency-free)`);
    process.exit(1);
  }

  const rewritten = source.replace(/(from\s+['"]\.\/[^'"]+?)(['"])/g, (match, path, quote) =>
    path.endsWith('.ts') ? match : `${path}.ts${quote}`,
  );
  writeFileSync(join(OUT, name), HEADER + rewritten);
  count++;
}

console.log(`domain:sync copied ${count} files to ${OUT}`);